# Stores the keyword dictionary with weights
KEYWORDS = {
    # Positive words/phrases
    "consistent": 2,
    "flow": 1,
    "coherent": 2,
    "uniform": 2,
    "structured": 2,
    "organized": 2,
    "steady": 1,
    "harmonious": 2,
    "logical progression": 3,
    "clear style": 3,
    "stable tone": 2,
    "single voice": 3,
    "formal English": 2,
    "descriptive language": 3,
    "clear writing style": 3,
    "precise details": 2,
    "proper punctuation": 2,
    "consistent tone": 3,
    "narrative style": 2,
    "cohesive structure": 3,
    "precision": 2,
    "uniform vocabulary range": 3,

    # Negative words/phrases
    "inconsistent": -3,
    "disjointed": -2,
    "fragmented": -3,
    "erratic": -2,
    "irregular": -2,
    "jarring": -2,
    "clashing": -2,
    "multiple styles": -3,
    "abrupt changes": -3,
    "conflicting tones": -3,
    "different voices": -3,
    "multiple authors": -3,
    "inconsistency across writing styles": -3,
    "variations in word length": -2,
    "different sentence structures": -2,
    "mixed lexical diversity": -2,
    "passive constructions": -1,
    "active constructions": -1,
    "higher readability score": -1,
    "lower readability score": -1,
    "uneven flow": -2,

    # Neutral/contextual
    "lexical diversity": -1,
    "readability score": -1,
    "sentence complexity": -1,
}

